### ISSUE TITLE
Implement interactive patch mode

### ISSUE THREAD

**Issue by nunofgs** [keis/git-fixup#18]
This is already an immensely useful project but it would be great if there was an interactive mode, similar to `git commit -p`.

Say you've modified a dozen files and not all of them will be fixed-up into the same commit. Right now you'll need to `add -p` a small portion and type `git fixup` to figure out where it will fit. Then rinse and repeat for every chunk/file.

Here's how I imagine the interactive mode working:

``` bash
$ git add <a dozen files>
$ git fixup -p

diff --git a/index.html b/index.html
index 4d07108..4335f49 100644
--- a/index.html
+++ b/index.html
@@ -16,7 +16,7 @@ Date Finder

-<div id="footer">contact support@github.com</div>
+<div id="footer">contact email.support@github.com</div>

Possible fixup candidates:

1. 01d39157c412399fcc1bce567edba30516f5212c [L] Update index <foo@bar.com>
2. aa734ad194dc6073a7b2c4123ba225a1e444191e [L] Initial commit <foo@bar.com>

Choose a fixup candidate [1,2,?]?
```

**Comment by keis** [comment]
Something like this would be really cool to have. I imagine it would have to do something clever to not end up with a bunch of fixups for the same commit.

Another thing to consider is what to use as input to figure out the suggestion. My initial thought would be to only use to hunk your looking at but that might miss the pretty useful case of adding a update to test case with the commit because that hunk is of course in a different file.

**Comment by nunofgs** [comment]
Agreed. I wouldn't mind if it created multiple fixups for the same commit since they are short-lived (just until the next rebase). We could leave that bit for a future improvement.

@fixe Care to take a shot at a PR?
