### ISSUE TITLE
Show all commits that touched changed lines (up to branch point)

### ISSUE THREAD

**Issue by mnieber** [keis/git-fixup#29]
The staged lines are not necessarily a fixup for the latest commit that touched these lines.  It would be nice if I could see a list of all commits (up to the point of the commit where my branch starts) that touched the lines that I staged.

**Comment by keis** [comment]
Agreed. that would be nice. But I think it could be quite complicated to implement because to my knowledge git does not provide any mechanisms for query for those commits.

Right now what I'm using is a simple git blame with a line range based on the staged changes. To get earlier commits the script would have to run repeatedly over a smaller and smaller rev range and somehow account for changes in line numbers. Which sounds very error prone and slow :(

I'll research this a bit and see if I can find anything. If you have any good ideas on how to solve this let me know :)

**Comment by mnieber** [comment]
It seems that I can already go a long way towards what I want by changing `-n 1` to `-n 10`:

    git rev-list -n 10 -E --invert-grep --grep='^(fixup|squash)' $rev_range -- $file
    git --no-pager log --format="%H [$type] %s <%ae>" -n 10 "$sha"

(I don't understand what this actually changes, I was just hacking into the script)

**Comment by keis** [comment]
So git-fixup actually uses two sources for commits. `fixup_candidates_files` is really simple and only grabs the most recent commit to a file while `fixup_candidates_lines` tries to be clever and actually consider the changed lines with git blame

The blame based source will usually provide the most relevant suggestions but its a bit picky, also suggesting the most recent commit makes it a bit more likely to find the one we want especially when blame produce few or none suggestions.

Grabbing the 10 most recent commits to each file, which is what your change does, it's even more likely to be included but you're probably getting pretty close to just having the full rev range to pick from. For the tool to be really useful the list needs to have a few good guesses only.
